# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20cac69c68fb2d2de64fe77514e3bc1cebfbc2dbcf078846d1e3d34dbeadbf22ee70f8e80bc30af053e93842c16201502bd310b2848d784d0927a98ad5981beb

test:
  secret_key_base: e57fda530e03d6844389010e5256f26491161851b25061cd4dc1ddc74c9af2e75352ba518b30bbfce6c113a98c3265bdaeeca85274324ea14a03458b4b253675

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
